#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DRY_RUN=false

if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=true
fi

log() {
  printf '[cleanup] %s\n' "$1"
}

run_cmd() {
  if $DRY_RUN; then
    printf '[cleanup][dry-run] %s\n' "$*"
  else
    eval "$@"
  fi
}

log "root: ${ROOT_DIR}"

# Clean Next build artifacts (safe to rebuild).
for path in \
  "${ROOT_DIR}/web/.next" \
  "${ROOT_DIR}/web/.next-preview"; do
  if [[ -e "$path" ]]; then
    run_cmd "rm -rf '$path'"
    log "removed $path"
  fi
done

# Remove historical next backup dirs generated by local dev.
if compgen -G "${ROOT_DIR}/web/.next_bak_*" >/dev/null; then
  while IFS= read -r backup_dir; do
    [[ -z "$backup_dir" ]] && continue
    run_cmd "rm -rf '$backup_dir'"
    log "removed $backup_dir"
  done < <(find "${ROOT_DIR}/web" -maxdepth 1 -type d -name '.next_bak_*' | sort)
fi

# Clean runtime temp files under logs but keep directory.
mkdir -p "${ROOT_DIR}/logs"
while IFS= read -r log_file; do
  [[ -z "$log_file" ]] && continue
  run_cmd "rm -f '$log_file'"
  log "removed $log_file"
done < <(find "${ROOT_DIR}/logs" -maxdepth 1 -type f \( -name '*.log' -o -name '*.pid' -o -name '*.tmp' \) | sort)

log "done"
